# Generated by Django 5.0.1 on 2024-01-30 16:20

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اسلایدر')),
                ('link', models.URLField(verbose_name='لینک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Products.models.upload_image, verbose_name='تصویر')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
        ),
    ]
