# Generated by Django 5.0.1 on 2024-01-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
    ]
