# Generated by Django 5.0.1 on 2024-01-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sliders', '0002_alter_slider_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='active',
        ),
    ]
