# Generated by Django 5.0.1 on 2024-02-02 15:22

import Settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=200, verbose_name='تلفن تماس')),
                ('mobile', models.CharField(max_length=150, verbose_name='شماره همراه')),
                ('fax', models.CharField(max_length=150, verbose_name='شماره فکس')),
                ('address', models.CharField(max_length=250, verbose_name='آدرس')),
                ('copy_right', models.CharField(max_length=250, verbose_name='متن کپی رایت')),
                ('about', models.TextField(verbose_name='درباره ما')),
                ('instagram', models.CharField(max_length=250, verbose_name='آدرس صفحه اینستراگرام')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=Settings.models.upload_image, verbose_name='تصویر')),
            ],
        ),
    ]
