# Generated by Django 5.0.1 on 2024-02-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'تنظیمات', 'verbose_name_plural': 'تنظیمات'},
        ),
    ]
