# Generated by Django 5.0.1 on 2024-01-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='products', to='Products.productimage', verbose_name='تصاویر گالری'),
        ),
    ]
