# Generated by Django 5.0.1 on 2024-01-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_category_options'),
        ('Products', '0005_alter_product_additional_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Category.category', verbose_name='دسته بندی'),
        ),
    ]
