# Generated by Django 5.0.1 on 2024-02-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_remove_product_additional_images_productgallery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='انتخاب محصول'),
        ),
    ]
