# Generated by Django 5.0.1 on 2024-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='تعداد مشاهده'),
        ),
    ]
